Fix typo: 因为即使 -> 因为如果可以的话
javascript-tutorial/zh.javascript.info pull request #1023
Opened 2022-03-13 07:19 UTC by moqimoqidea

**目标章节**：例如 1-js/01-getting-started/1-intro

**当前上游最新 commit**：此处填写本项目英文版 https://github.com/javascript-tutorial/en.javascript.info 的最新 commit，例如 https://github.com/javascript-tutorial/zh.javascript.info/commit/b03ca00a992a73aaf213970e71f74ac1c04def33

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
无

2022-03-13 08:33 UTC, songhn233 requested changes

2022-03-13 08:33 UTC, songhn233 commented on 2-ui/1-document/08-styles-and-classes/article.md
> +但 `getComputedStyle` 没有给出访问该颜色的方式，因为如果可以的话，任意页面都可以通过在页面上创建它，并通过检查样式来确定用户是否访问了某链接。
```suggestion
但 `getComputedStyle` 没有给出访问该颜色的方式，因为如果可以的话，任意页面都可以通过在页面上创建它，并通过检查样式来确定用户是否访问了某链接。
```
```suggestion
但 `getComputedStyle` 没有给出访问该颜色的方式，因为如果允许的话，任意页面都可以通过在页面上创建它，并通过检查样式来确定用户是否访问了某链接。
```

2022-03-13 10:41 UTC, songhn233 approved these changes

2022-04-14 01:17 UTC, leviding approved these changes

2022-04-14 01:17 UTC, merged