improve translation
javascript-tutorial/zh.javascript.info pull request #1050
Opened 2022-05-19 07:17 UTC by stosSe4r

试着改动了一些用词，调整了一部分句子的结构

**目标章节**：[1-js/05-data-types/10-destructuring-assignment](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/1-js/05-data-types/10-destructuring-assignment)

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/246156d6e24d0d79e4acf4b663c63adf130bff27

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 参考英文版内容改进中文翻译

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2022-05-19 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1050) it.</sub>

2022-05-19 13:16 UTC, songhn233 requested changes

2022-05-19 13:16 UTC, songhn233 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> +用于 `Map` 的类似代码更简单，因为Map是可迭代的：
```suggestion
用于 `Map` 的类似代码更简单，因为 Map 是可迭代的：
```

2022-05-19 13:16 UTC, songhn233 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> +在实际开发中，记忆如此多的参数的位置是一个很大的负担。通常IDE会尽力帮助我们，特别是当代码有良好的文档注释的时候，但是…… 另一个问题就是，在大部分的参数只需采用默认值的情况下，调用这个函数时会需要写大量的undefined。
```suggestion
在实际开发中，记忆如此多的参数的位置是一个很大的负担。通常集成开发环境（IDE）会尽力帮助我们，特别是当代码有良好的文档注释的时候，但是…… 另一个问题就是，在大部分的参数只需采用默认值的情况下，调用这个函数时会需要写大量的 undefined。
```

2022-05-19 13:16 UTC, songhn233 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> +变量的顺序并不重要，下面这个代码和上面的效果一致：
```suggestion
变量的顺序并不重要，下面这个代码也是等价的：
```

2022-05-19 13:16 UTC, songhn233 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> +通常，如果数组比左边的列表长，那么“多出来的”的数组项会被省略。
```suggestion
通常，如果数组比左边的列表长，那么“其余”的数组项会被省略。
```

既然标题是 `其余的 '...'` 那这块都统一吧

2022-05-19 16:02 UTC, songhn233 approved these changes
Thanks.

2022-05-22 03:08 UTC, leviding commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> +我们可以使用这些变量而非原来的数组成员了。
```suggestion
我们可以使用这些变量而非原来的数组项了。
```

这样是否会更好？

2022-05-22 04:02 UTC, leviding approved these changes

2022-05-22 04:03 UTC, merged