improve translation
javascript-tutorial/zh.javascript.info pull request #1051
Opened 2022-05-19 17:11 UTC by stosSe4r

调整部分用词和句子结构。

**目标章节**：[1-js / 05-data-types / 11-date](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/1-js/05-data-types/11-date)

**当前上游最新 commit**：https://github.com/javascript-tutorial/zh.javascript.info/commit/2901e0c64590a67d8a2bde1ea76a514d96f80469

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 参考英文版内容改进翻译

2022-05-19 19:23 UTC, songhn233 requested changes

2022-05-19 19:23 UTC, songhn233 commented on 1-js/05-data-types/11-date/article.md
> +看起来使用 `getTime()` 这种方式快得多，原因是它没有类型转化，这样对引擎优化来说更加简单。
```suggestion
看起来使用 `getTime()` 这种方式快得多，这是因为它没有进行类型转化，对引擎优化来说更加简单。
```

2022-05-19 19:23 UTC, songhn233 commented on 1-js/05-data-types/11-date/article.md
> +<http://mrale.ph> 提供了许多关于 V8 引擎的文章。
```suggestion
<http://mrale.ph> 提供了许多 V8 引擎相关的文章。
```

2022-05-19 19:23 UTC, songhn233 commented on 1-js/05-data-types/11-date/article.md
> +Node.js 提供 `microtime` 模块以及其他方法。原则上几乎所有的设备和环境都允许获取更高精度的时间数值，不过需要从 `Date` 以外的对象获取。
```suggestion
Node.js 可以通过 `microtime` 模块或使用其他方法。从技术上讲，几乎所有的设备和环境都允许获取更高精度的时间数值，只不过 `Date` 不是这样设计的。
```

原意是 Node.js 可以通过 microtime 模块或其他方式获取更精确的时间。`提供` 不太合适，因为 `microtime` 不是官方依赖。`原则上` 也不太合适，因为本意就是技术上讲各种设备都能得到比较精确的时间，而 `Date` 只能获取低精度、相对不准确的时间。

2022-05-19 20:32 UTC, stosSe4r commented on 1-js/05-data-types/11-date/article.md
> +Node.js 提供 `microtime` 模块以及其他方法。原则上几乎所有的设备和环境都允许获取更高精度的时间数值，不过需要从 `Date` 以外的对象获取。
嗯，这两个修改欠考虑了

2022-05-19 20:33 UTC, stosSe4r commented
/done

2022-05-20 04:26 UTC, songhn233 approved these changes
Thanks.

2022-05-22 03:18 UTC, leviding requested changes

2022-05-22 03:18 UTC, leviding commented on 1-js/05-data-types/11-date/article.md
> +调用 `new Date()`来创建一个新的 `Date` 对象。在调用时可以带有一些参数，如下所示：
```suggestion
调用 `new Date()` 来创建一个新的 `Date` 对象。在调用时可以带有一些参数，如下所示：
```

2022-05-22 03:18 UTC, leviding commented on 1-js/05-data-types/11-date/article.md
> +它相当于 `new Date().getTime()`，但它不会创建中间的 `Date` 对象。因此它更快，而且不会对垃圾收集器造成额外的压力。
```suggestion
它相当于 `new Date().getTime()`，但它不会创建中间的 `Date` 对象。因此它更快，而且不会对垃圾回收造成额外的压力。
```

收集器只是一个工具，其实是对浏览器性能造成压力。

2022-05-22 03:18 UTC, leviding commented on 1-js/05-data-types/11-date/article.md
> +看起来使用 `getTime()` 这种方式快得多，这是因为它没有进行类型转化，对引擎优化来说更加简单。
```suggestion
看起来使用 `getTime()` 这种方式快得多，这是因为它没有进行类型转换，对引擎优化来说更加简单。
```

2022-05-22 03:18 UTC, leviding commented on 1-js/05-data-types/11-date/article.md
> +<http://mrale.ph> 提供了许多 V8 引擎相关的文章。
```suggestion
<http://mrale.ph> 提供了很多 V8 引擎相关的文章。
```

2022-05-22 03:18 UTC, leviding commented on 1-js/05-data-types/11-date/article.md
> +Node.js 可以通过 `microtime` 模块或使用其他方法。从技术上讲，几乎所有的设备和环境都允许获取更高精度的时间数值，只不过 `Date` 不是这样设计的。
```suggestion
Node.js 可以通过 `microtime` 模块或使用其他方法。从技术上讲，几乎所有的设备和环境都允许获取更高精度的时间数值，只不过不是使用 `Date` 对象。
```

2022-05-22 03:44 UTC, stosSe4r commented
/done

2022-05-22 04:04 UTC, leviding approved these changes
Thanks!

2022-05-22 04:04 UTC, merged