fix: typo error
javascript-tutorial/zh.javascript.info pull request #1052
Opened 2022-05-20 08:52 UTC by xlzy520

**目标章节**：1-js/02-first-steps/10-ifelse/article.md

**当前上游最新 commit**：[https://github.com/javascript-tutorial/en.javascript.info/commit/2b79ab1ff8cf44a5802cd0cd204921276b650c03](https://github.com/javascript-tutorial/en.javascript.info/commit/2b79ab1ff8cf44a5802cd0cd204921276b650c03)

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 修改语句，从语境上来说，这里更适合的意思应该是，`这一个或那一个，这一个或另一个`，而不是简单的将原文的`one`翻译成`一个`

2022-05-20 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1052) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1052) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1052) it.</sub>

2022-05-20 08:54 UTC, songhn233 requested changes

2022-05-20 08:54 UTC, songhn233 commented on 1-js/02-first-steps/10-ifelse/article.md
> +问号 `?` 的作用是根据条件返回这一个或另一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
我觉得原来的比较符合意思，`这一个` 反而不太清楚？

可以解释一下

2022-05-20 08:59 UTC, xlzy520 commented on 1-js/02-first-steps/10-ifelse/article.md
> +问号 `?` 的作用是根据条件返回这一个或另一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
中文语境下，一般不是说 这个或那个，这个人，那个人。`一个`是一个量词，并不指代某个对象。原文 one value or another.   or another意思是   或者另一个， a  或者 b。那么a 与 b 应该是一个词性？

2022-05-20 09:04 UTC, xlzy520 commented on 1-js/02-first-steps/10-ifelse/article.md
> +问号 `?` 的作用是根据条件返回这一个或另一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
改成 `返回其中一个值或另一个值`可能要更好

2022-05-20 09:09 UTC, xlzy520 commented on 1-js/02-first-steps/10-ifelse/article.md
> +问号 `?` 的作用是根据条件返回这一个或另一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
咨询了一下英语专业的朋友，英语的`one`是有指代的意思的，one可以表示其中的某一个，所以可以使用 one or another。但是中文里面 `一个`只是一个量词。我现在更倾向改成`返回其中一个值或另一个值`。

2022-05-20 09:14 UTC, songhn233 commented on 1-js/02-first-steps/10-ifelse/article.md
> +问号 `?` 的作用是根据条件返回这一个或另一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
```suggestion
问号 `?` 的作用是根据条件返回其中一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
```
我觉得没必要严格翻译出另一个，这句话重点是前调问号表达式用来获取值而不是执行语句

2022-05-20 09:15 UTC, xlzy520 commented on 1-js/02-first-steps/10-ifelse/article.md
> +问号 `?` 的作用是根据条件返回这一个或另一个值。请正确使用它。当需要执行不同的代码分支时，请使用 `if`。
是的，那我应该点commit suggestion吗

2022-05-20 09:52 UTC, songhn233 approved these changes

2022-05-22 03:18 UTC, leviding approved these changes

2022-05-22 03:19 UTC, merged