improve translation
javascript-tutorial/zh.javascript.info pull request #1053
Opened 2022-05-25 07:30 UTC by stosSe4r

修改了一些用词和句子结构。

**目标章节**：[1-js/06-advanced-functions/02-rest-parameters-spread](https://github.com/javascript-tutorial/zh.javascript.info/tree/master/1-js/06-advanced-functions/02-rest-parameters-spread)

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/2efe0dce18a57f2b6121ed6656d6fe10b0ee8f96

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 参考英文版改进翻译

2022-06-09 11:08 UTC, songhn233 requested changes

2022-06-09 11:08 UTC, songhn233 commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +这种方式比使用 `let arrCopy = Object.assign([], arr)` 复制数组，或使用 `let objCopy = Object.assign({}, obj)` 复制对象较为简便。因此，只要情况允许，我们倾向于使用它。
```suggestion
这种方式比使用 `let arrCopy = Object.assign([], arr)` 复制数组，或使用 `let objCopy = Object.assign({}, obj)` 复制对象来说更为简便。因此，只要情况允许，我们倾向于使用它。
```

2022-06-09 11:08 UTC, songhn233 commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +有时我们也需要与之相反的语法。
这里感觉不适合调整成强调 **语法**。保持原文似乎并没有问题吧？

2022-06-09 12:26 UTC, stosSe4r commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +有时我们也需要与之相反的语法。
> 这里感觉不适合调整成强调 **语法**。保持原文似乎并没有问题吧？

好的，原文的翻法我也能接受
这个句子（可能因为有儿化音）感觉有点不符合上下文语气，我再回去顺一遍

2022-06-09 12:33 UTC, stosSe4r commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +有时我们也需要与之相反的语法。
已撤回127行的改动。
129行“不过”和“相反”似乎语义上重复了，考虑删去“不过”以简化句子结构，删去儿化音以匹配周围的选词。

2022-06-09 15:04 UTC, songhn233 approved these changes
LGTM

2022-06-11 06:08 UTC, stosSe4r commented
/done

2022-07-03 05:26 UTC, leviding requested changes

2022-07-03 05:26 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +在本章中，我们将学习如何编写可传入任意数量参数的函数，以及如何将数组作为参数传递给这类函数。
```suggestion
在本章中，我们将学习如何编写支持传入任意数量参数的函数，以及如何将数组作为参数传递给这类函数。
```

2022-07-03 05:26 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +直接传入这个数组是不会奏效的，因为 `Math.max` 期望一列数值型的参数，而不是一个数组：
```suggestion
直接“原样”传入这个数组是不会奏效的，因为 `Math.max` 期望的是 list 形式的数值型参数，而不是一个数组：
```

2022-07-03 05:26 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +**Spread 语法** 可以解决这个问题。它看起来和 rest 参数很像，也使用 `...`，但是二者的用途完全相反。
```suggestion
**Spread 语法** 可以解决这个问题！它看起来和 rest 参数很像，也使用 `...`，但是二者的用途完全相反。
```

2022-07-03 05:26 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +在上面的示例中，我们使用 spread 语法展开了一些数组。其实任何可迭代对象都可以使用 spread 语法展开。
```suggestion
在上面的示例中，我们使用数组展示了 spread 语法，其实我们可以用 spread 语法这样操作任何可迭代对象。
```

2022-07-03 05:26 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +对于这个特定任务，我们还可以使用 `Array.from` 来完成，因为该方法会将一个可迭代对象（如字符串）转换为数组：
```suggestion
对于这个特定任务，我们还可以使用 `Array.from` 来实现，因为该方法会将一个可迭代对象（如字符串）转换为数组：
```

2022-07-03 05:26 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +注意 `Array.from(obj)` 和 `[...obj]` 存在一个细微的差别：
```suggestion
不过 `Array.from(obj)` 和 `[...obj]` 存在一个细微的差别：
```

2022-07-11 04:50 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +这个函数不会因为传入过多的参数而报错。当然，只有前两个参数被求和了。
```suggestion
虽然这里这个函数不会因为传入过多的参数而报错。但是，当然，只有前两个参数被求和了。
```

2022-07-11 04:56 UTC, leviding commented on 1-js/06-advanced-functions/02-rest-parameters-spread/article.md
> +直接“原样”传入这个数组是不会奏效的，因为 `Math.max` 期望的是 list 形式的数值型参数，而不是一个数组：
```suggestion
直接“原样”传入这个数组是不会奏效的，因为 `Math.max` 期望的是列表形式的数值型参数，而不是一个数组：
```

2022-07-11 05:32 UTC, merged