translate: 2-ui/1-document/07-modifying-document
javascript-tutorial/zh.javascript.info pull request #1077
Opened 2022-07-06 14:06 UTC by printfinn

**目标章节**：2-ui/1-document/07-modifying-document

**当前上游最新 commit**：

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 修改部分错误

里面还有个`[old]`, 我没找到在哪翻译.

2022-07-06 14:34 UTC, songhn233 requested changes

2022-07-06 14:34 UTC, songhn233 commented on 2-ui/1-document/07-modifying-document/article.md
> +为了让 `div` 显示出来，我们需要将其插入到 `document` 中的某处。例如，插入到 `<body>` 元素里, 用 `document.body` 来操作这个元素。
```suggestion
为了让 `div` 显示出来，我们需要将其插入到 `document` 中的某处。例如，插入到 `<body>` 元素里。
```
这块我倾向于把后面的 `document.body` 不翻译，这样不影响理解。现在这种描述感觉不太看的懂。

2022-07-06 15:22 UTC, songhn233 requested changes

2022-07-06 15:22 UTC, songhn233 commented on 2-ui/1-document/07-modifying-document/article.md
> +- `"beforebegin"` — 将 `html` 插入到 `elem` 正上方，
```suggestion
- `"beforebegin"` — 将 `html` 插入到 `elem` 之前，
```

2022-07-06 15:22 UTC, songhn233 commented on 2-ui/1-document/07-modifying-document/article.md
> +- `"afterend"` — 将 `html` 插入到 `elem` 正下方。
```suggestion
- `"afterend"` — 将 `html` 插入到 `elem` 之后。
```

2022-07-06 22:55 UTC, printfinn commented
/done

2022-07-07 04:55 UTC, printfinn commented on 2-ui/1-document/07-modifying-document/article.md
> +- `"beforebegin"` — 将 `html` 插入到 `elem` 正上方，
Done done~

2022-07-08 03:52 UTC, leviding commented on 2-ui/1-document/07-modifying-document/article.md
> +ul.append(...getListContent()); // append + "..." 是我们的好朋友!
```suggestion
ul.append(...getListContent()); // append + "..." operator = friends!
```

2022-07-08 03:52 UTC, leviding commented on 2-ui/1-document/07-modifying-document/article.md
> +为了让 `div` 显示出来，我们需要将其插入到 `document` 中的某处。例如，插入到 `<body>` 元素里。
```suggestion
为了让 `div` 显示出来，我们需要将其插入到 `document` 中的某处。例如，通过 `document.body` 将其插入到 `<body>` 元素里。
```

2022-07-08 06:51 UTC, printfinn commented on 2-ui/1-document/07-modifying-document/article.md
> +ul.append(...getListContent()); // append + "..." 是我们的好朋友!
我想作者是想在注释中让大伙记住append + ...的用法? 不需要翻译吗?

2022-07-08 06:52 UTC, printfinn commented on 2-ui/1-document/07-modifying-document/article.md
> +为了让 `div` 显示出来，我们需要将其插入到 `document` 中的某处。例如，插入到 `<body>` 元素里。
@songhn233 你俩battle一下😄

2022-07-08 08:21 UTC, leviding commented on 2-ui/1-document/07-modifying-document/article.md
> +ul.append(...getListContent()); // append + "..." 是我们的好朋友!
> 我想作者是想在注释中让大伙记住append + ...的用法? 不需要翻译吗?

这里不需要翻译

2022-07-08 09:19 UTC, songhn233 approved these changes

2022-07-08 10:44 UTC, leviding commented on 2-ui/1-document/07-modifying-document/article.md
> +为了让 `div` 显示出来，我们需要将其插入到 `document` 中的某处。例如，插入到 `<body>` 元素里。
> @songhn233 你俩battle一下😄

1. 尊重原文
2. 通过 `document.body` 是有用的信息，告知读者以什么样的方式插入

2022-07-09 02:27 UTC, leviding approved these changes

2022-07-09 02:28 UTC, merged