fix: typo
javascript-tutorial/zh.javascript.info pull request #1103
Opened 2022-09-21 14:59 UTC by zhouzhaonan

**目标章节**：2-ui/99-ui-misc/02-selection-range

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/c2342c1290bf8e068050c8549ff374093e4819c5

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 修改部分错误

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2022-09-21 14:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1103) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1103) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1103) it.</sub>

2022-09-21 15:58 UTC, songhn233 approved these changes
LGTM

2022-09-25 17:17 UTC, songhn233 approved these changes
LGTM

2022-10-02 07:18 UTC, songhn233 requested changes
涉及到的点有些多，建议还是按照章节拆开来提pr

2022-10-30 07:21 UTC, leviding approved these changes
LGTM.

2022-10-30 07:22 UTC, merged