feat: update translation
javascript-tutorial/zh.javascript.info pull request #1110
Opened 2022-10-10 03:13 UTC by rfhits

**目标章节**：例如 2-ui/1-document/11-coordinates

**当前上游最新 commit**：无

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无| “to show”应当翻译为“展示”。“展示”和“显示”相比，更能体现人“主动”修改页面、呈现新元素的意思。

2022-10-10 03:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1110) it.</sub>

2022-10-13 03:54 UTC, songhn233 requested changes
感觉这样会好一点?
"一个" 不需要翻译, "些什么" 感觉有点太口语化了

2022-10-13 03:54 UTC, songhn233 commented on 2-ui/1-document/11-coordinates/article.md
> +为了在一个元素附近展示些什么，我们可以使用 `getBoundingClientRect` 来获取这个元素的坐标，然后使用 CSS `position` 以及 `left/top`（或 `right/bottom`）。
```suggestion
想要在元素附近展示东西，我们可以使用 `getBoundingClientRect` 来获取这个元素的坐标，然后使用 CSS `position` 以及 `left/top`（或 `right/bottom`）。
```

2022-10-30 11:09 UTC, leviding approved these changes

2022-10-30 11:10 UTC, merged