翻译文章 `Unicode, String internals`
javascript-tutorial/zh.javascript.info pull request #1125
Opened 2022-10-31 03:00 UTC by situ2001

**目标章节**：1-js/99-js-misc/06-unicode

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/5dff42ba283bce883428c383c080fa9392b71df8

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | d9f659e | 文章翻译

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2022-10-31 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1125) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1125) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1125) it.</sub>

2022-12-02 21:40 UTC, songhn233 requested changes

2022-12-02 21:40 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +本节将更深入地介绍字符串的内部原理。 如果你打算处理表情符号(emoji)、稀有的数学、象形文字字符或其他稀有符号，这些知识将对你很有用。
```suggestion
本节将更深入地介绍字符串的内部原理。 如果你打算处理表情符号(emoji)、罕见的数学、象形文字字符或其他稀有字符，这些知识将对你很有用。
```

搜索引擎来看“稀有字符”这个描述会更常见一点

2022-12-02 21:40 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +正如我们所知，JavaScript 的字符串是基于 [Unicode](https://en.wikipedia.org/wiki/Unicode) 的：每一个字符是用 1-4 字节长度的字节序列表示的。
感觉这里原文的描述可能就有歧义？
冒号后面应该是对前文的解释，但是我理解 unicode 本身只是一个字符集，而 1-4 字节这是在解释 UTF-8 等具体的编码了

2022-12-02 21:40 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +JavaScript 允许我们使用下述三种表示方法之一指定十六进制 Unicode 码以将一个字符插入到字符串里。
```suggestion
JavaScript 允许我们使用下述三种方式将一个 Unicode 字符以十六进制表示插入到字符串中。
```

2022-12-02 21:40 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +    `XX` 必须是介于 `00` 与 `FF` 之间的两位十六进制数， 此时， `\xXX` 便表示 Unicode 码为 `XX 的字符。
```suggestion
    `XX` 必须是介于 `00` 与 `FF` 之间的两位十六进制数， `\xXX` 表示 Unicode 码为 `XX` 的字符。
```

2022-12-02 21:40 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +    这前 256 个字符包括拉丁字母、最基本的语法字符和其他一些字符。 例如，`"\x7A"` 与 `"z"` (Unicode 为 `U+007A`) 是同一个字符。
```suggestion
    这前 256 个字符包括拉丁字母、最基本的语法字符和其他一些字符。 例如，`"\x7A"` 表示 `"z"` (Unicode 为 `U+007A`) 。
```

2022-12-02 21:40 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +    `XXXX` 必须是 4 位十六进制数，值介于 `0000` 和 `FFFF` 之间。此时， `\uXXXX` 便表示为 Unicode 代码为 `XXXX` 的字符。
```suggestion
    `XXXX` 必须是 4 位十六进制数，值介于 `0000` 和 `FFFF` 之间。此时， `\uXXXX` 便表示 Unicode 代码为 `XXXX` 的字符。
```

2022-12-03 11:11 UTC, songhn233 requested changes

2022-12-03 11:11 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +    alert( "\u{1F60D}" ); // 😍, 一个微笑符号 (另一个长 Unicode)
```suggestion
    alert( "\u{20331}" ); // 佫, 一个不常见的中文字符
    alert( "\u{1F60D}" ); // 😍, 一个微笑符号
```

2022-12-03 11:11 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +所有常用字符都有 2 字节代码（4 个十六进制数字）。 大多数欧洲语言的字母，数字，以及基本统一了的 CJK 表意文字集（CJK——来自中文、日文和韩文书写系统）中的字母用 2 字节表示。
```suggestion
所有常用字符都有 2 字节编码（4 个十六进制数字）。 大多数欧洲语言的字母，数字，以及基本统一的 CJK 表意文字集（CJK——来自中文、日文和韩文书写系统）中的字母用 2 字节表示。
```

2022-12-03 11:11 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +要想获取这些符号，也是一个棘手的问题：在大多数语言特性里，代理对是被当成两个单独的字符对待的。
```suggestion
要想获取这些符号，也是一个棘手的问题：在大多数编程语言里，代理对是被当成两个单独的字符对待的。
```

2022-12-03 11:11 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +从技术层面上讲，可以通过代码来检测到代理对的存在：如果一个字符的代码在 `0xd800..0xdbff` 这个区间内，那么它就是代理对的前一部分。 下一个字符（第二部分）的代码必须在区间 `0xdc00..0xdfff` 内。 这些预留的区间是标准专门为代理对制定的，
```suggestion
从技术层面上讲，可以通过代码来检测到代理对的存在：如果一个字符的代码在 `0xd800..0xdbff` 这个区间内，那么它就是代理对的前一部分。 下一个字符（第二部分）的代码必须在区间 `0xdc00..0xdfff` 内。 这些区间是标准专门为代理对预留的，
```

2022-12-03 11:11 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +// codePointAt 会注意到代理对的存在
```suggestion
// codePointAt 会正确处理代理对
```

2022-12-03 11:11 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +// charCodeAt 不会注意到代理对的存在, 所以返回了 𝒳 前半部分的代码:
```suggestion
// charCodeAt 不会考虑代理对, 所以返回了 𝒳 前半部分的代码:
```

2022-12-04 11:24 UTC, situ2001 commented on 1-js/99-js-misc/06-unicode/article.md
> +正如我们所知，JavaScript 的字符串是基于 [Unicode](https://en.wikipedia.org/wiki/Unicode) 的：每一个字符是用 1-4 字节长度的字节序列表示的。
合理一点的翻译应该是：
JavaScript 的字符串是基于 [Unicode](https://en.wikipedia.org/wiki/Unicode) 的。**在 JavaScript 里**，每一个字符是用 1-4 字节长度的字节序列表示的。

2022-12-04 17:35 UTC, songhn233 requested changes

2022-12-04 17:35 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +# Unicode —— 字符串的内部原理
```suggestion
# Unicode —— 字符串内幕
```

2022-12-04 17:35 UTC, songhn233 commented on 1-js/99-js-misc/06-unicode/article.md
> +正如我们所知，JavaScript 的字符串是基于 [Unicode](https://en.wikipedia.org/wiki/Unicode) 的：每一个字符是用 1-4 字节长度的字节序列表示的。
```suggestion
正如我们所知，JavaScript 的字符串是基于 [Unicode](https://en.wikipedia.org/wiki/Unicode) 的。同时，每一个字符是用 1-4 字节长度的字节序列表示的。
```

2022-12-05 01:53 UTC, situ2001 commented
/done

2022-12-05 04:01 UTC, songhn233 approved these changes

2022-12-11 17:23 UTC, leviding commented
Review 中，还需要点时间。

2022-12-17 10:53 UTC, leviding requested changes
@briskr

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +你将会在 <info:iterable> 一章找到更多处理代理对的方法。 如今可能会有专门处理代理对的库，但没有足够流行到让我们可以在这里安利的库。
```suggestion
你稍后可以在 <info:iterable> 一章中找到更多处理代理对的方式。可能也有专门处理代理对的库，但没有足够流行到可以让我们在这里推荐的库。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +````warn header="注意：在任意点拆分字符串是危险的"
```suggestion
````warn header="注意：在任意点拆分字符串是很危险的"
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +我们不能只在任意位置拆分字符串，例如 从 `str.slice(0, 4)` 取出一个字符串，并期待它是一个有效的字符串，例如：
```suggestion
我们不能随意在任意位置对字符串进行拆分，例如通过 `str.slice(0, 4)` 获取一个字符串，并期待它是一个有效的字符串：
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +在这里，我们看到一个没有意义的垃圾字符被打印了出来（微笑表情代理对的前半部分）。
```suggestion
在这里，我们看到一个没有意义的垃圾字符被打印了出来（笑哭表情代理对的前半部分）。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +如果你打算可靠地使用代理对，请注意这一点。 这可能并不是什么大问题，但至少你应该得明白什么会发生。
```suggestion
如果你期望可靠地使用代理对，请注意这一点。这可能并不是什么大问题，但至少你应该知道发生了什么。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +## 变音符号与规范化
```suggestion
## 变音符号和规范化
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +许多语言会有由基本字符以及上标记/下标记组成的符号。
```suggestion
很多语言都有由基础字符及其上方/下方的标记所组成的符号。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +举个例子，`àáâäãåā` 这些字符是基于字母 `a` 得来的。
```suggestion
举个例子，字母 `a` 就是这些字符 `àáâäãåā` 的基础字符。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +常见的“复合”字符在 Unicode 表中都有自己的代码。 但不是所有这些字符都有自己的代码，因为可能的组合有太多了。
```suggestion
大多数常见的“复合”字符在 Unicode 表中都有自己的编码。但不是所有这些字符都有自己的编码，因为可能的组合形式太多了。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +为了支持任意的组合，Unicode 标准允许我们使用多个 Unicode 字符：基本字符后跟一个或多个“装饰”它的“标记”字符。
```suggestion
为了支持任意的组合，Unicode 标准允许我们使用多个 Unicode 字符：基础字符后跟着一个或多个“装饰”它的“标记”字符。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +例如，如果我们在 `S` 后跟特殊的“上句点”字符（代码为 `\u0307`），则显示为 Ṡ。
```suggestion
例如，如果我们在 `S` 后附加上特殊的“上方的点”字符（编码为 `\u0307`），则显示为 Ṡ。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +我们只需添加必要的标记字符，便可在字母上方（或下方）添加额外的标记。
```suggestion
如果我们需要在字母上方（或下方）添加一个额外的标记 —— 很简单，只需添加必要的标记字符即可。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +例如，如果我们附加一个字符“下句点”（代码 `\u0323`），那么我们将得到“有上下句点的 S”：`Ṩ`。
```suggestion
例如，如果我们继续在后面附加一个“下方的点”符号（编码 `\u0323`），那么我们将得到一个“上下都有一个点符号的 S”：`Ṩ`。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +如下代码所示：
```suggestion
就像这样：
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +这非常灵活，但也带来了一个有趣的问题：两个字符在我们眼里看起来虽然相同，却用着不同的 Unicode 组合表示。
```suggestion
这提供了极大的灵活性，但也带来了一个有趣的问题：两个字符可能在视觉上看起来相同，但却使用的是不同的 Unicode 组合。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +let s1 = 'S\u0307\u0323'; // Ṩ, S + 上句点 + 下句点
```suggestion
let s1 = 'S\u0307\u0323'; // Ṩ, S + 上方点符号 + 下方点符号
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +let s2 = 'S\u0323\u0307'; // Ṩ, S + 下句点 + 上句点
```suggestion
let s2 = 'S\u0323\u0307'; // Ṩ, S + 下方点符号 + 上方点符号
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +alert( s1 == s2 ); // 这两个字符在我们眼里看起来是相同的，却打印出了 false（？！）
```suggestion
alert( s1 == s2 ); // 尽管这两个字符在我们看来是相通的，但结果却是 false
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +“Unicode 规范化”算法可以解决问题，该算法将每个字符串转换为单一的“正常”形式。
```suggestion
“Unicode 规范化”算法可以解决这个问题，该算法将每个字符串转换为单一的“规范的”形式。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +[str.normalize()](mdn:js/String/normalize) 实现了该算法。
```suggestion
可以借助 [str.normalize()](mdn:js/String/normalize) 实现这一点。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +有意思的是，`normalize()` 将 3 个字符的序列组合在了一起：`\u1e68`（带有上下两个点的 S）。
```suggestion
有意思的是，在我们这个例子中，`normalize()` 将 3 个字符的序列合并为了一个字符：`\u1e68`（带有上下两个点的 S）。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +但实际并非总是如此。 原因是符号 `Ṩ` 是“足够常见的”，因此 Unicode 创建者将其包含在主表里，并为其提供了代码。
```suggestion
但实际并非总是如此。出现这种情况的原因是符号 `Ṩ` 是“足够常见的”，所以 Unicode 创建者将其囊括在了 Unicode 主表中，并为其提供了对应的编码。
```

2022-12-17 10:53 UTC, leviding commented on 1-js/99-js-misc/06-unicode/article.md
> +如果您想了解更多关于 Unicode 规范化规则和变体的信息，可以参阅 Unicode 标准的附录：[Unicode 规范化形式](https://www.unicode.org/reports/tr15/)。但就实用而言，本节中的信息就已经足够了。
```suggestion
如果你想了解关于 Unicode 规范化规则和变体的更多信息，可以参阅 Unicode 标准的附录中的内容：[Unicode 规范化形式](https://www.unicode.org/reports/tr15/)。但就实用而言，本节中的信息就已经足够了。
```

2022-12-21 15:34 UTC, situ2001 commented
/done

2022-12-26 08:07 UTC, merged

2022-12-26 08:07 UTC, leviding commented
Thanks all!