fix: translation of 1-js/03-code-quality/01-debugging-chrome/article.md
javascript-tutorial/zh.javascript.info pull request #1135
Opened 2022-12-11 10:19 UTC by leviding

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | / | 修改部分错误

2022-12-11 10:20 UTC, leviding commented
resolve #1133

2022-12-11 10:36 UTC, songhn233 approved these changes

2022-12-11 15:24 UTC, Username-Adrian requested changes
私以为将“运行下一条指令”全部改为“运行当前行指令”会更好。原因如下：
 “运行当前行指令”这句话足够简单明了地说明“Step”这个命令。当时在不了解“调试按钮”功能的时候，直接看本教程对“调试按钮”的解释，但是教程中的“下一条指令”的这些词语无法在我的脑海里和“调试按钮”的实际效果建立联系。
比如，在单击“调试按钮” F9 的时候，调试的实际效果是：调试光标的所在行指令运行了，且将光标移到了下一行。如果使用“运行下一行指令”来解释上述调试的实际效果，会发现：用这个“下一行指令”来指代“调试光标的所在行指令”是很难理解的。

2022-12-11 17:11 UTC, leviding commented
> 私以为将“运行下一条指令”全部改为“运行当前行指令”会更好。原因如下： “运行当前行指令”这句话足够简单明了地说明“Step”这个命令。当时在不了解“调试按钮”功能的时候，直接看本教程对“调试按钮”的解释，但是教程中的“下一条指令”的这些词语无法在我的脑海里和“调试按钮”的实际效果建立联系。 比如，在单击“调试按钮” F9 的时候，调试的实际效果是：调试光标的所在行指令运行了，且将光标移到了下一行。如果使用“运行下一行指令”来解释上述调试的实际效果，会发现：用这个“下一行指令”来指代“调试光标的所在行指令”是很难理解的。

个人认为“运行当前行”失去了 step 的含义，将吓一跳和当前行的概念揉在了一起，失去了原意。

运行下一条（即当前行）虽然相比运行当前行的表述理解难度提升，但保留了 step 本身的向后的含义，以及尊重了英文原文

2022-12-12 06:33 UTC, Username-Adrian approved these changes

2022-12-12 06:34 UTC, Username-Adrian approved these changes

2022-12-13 11:32 UTC, merged

2022-12-13 11:32 UTC, leviding commented
Thanks all!