fix: typo
javascript-tutorial/zh.javascript.info pull request #1156
Opened 2023-05-20 06:25 UTC by liuchengwucn

**目标章节**：1-js/05-data-types/12-json

**当前上游最新 commit**：无

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 更正翻译

2023-05-20 06:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1156) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1156) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1156) it.</sub>

2023-05-20 15:29 UTC, songhn233 approved these changes

2023-05-21 09:37 UTC, liuchengwucn commented
**目标章节**：1-js/06-advanced-functions/10-bind

**当前上游最新 commit**：[c09efa8](https://github.com/javascript-tutorial/en.javascript.info/commit/c09efa86be81728c565908c9d0d66c43f767b07b)

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | [c09efa8](https://github.com/javascript-tutorial/en.javascript.info/commit/c09efa86be81728c565908c9d0d66c43f767b07b) | 英文原文为“What if we'd like to fix some arguments, but not the context `this`?”，原翻译“但是这里没有上下文”不是很通顺。

2023-05-21 09:53 UTC, liuchengwucn commented
**目标章节**：1-js/06-advanced-functions/10-bind

**当前上游最新 commit**：733ff69
**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 733ff69 | 英文原文为“and first arguments if given.”，原翻译“第一个参数”有误。

2023-05-21 15:20 UTC, songhn233 requested changes

2023-05-21 15:20 UTC, songhn233 commented on 1-js/06-advanced-functions/10-bind/article.md
> +方法 `func.bind(context, ...args)` 返回函数 `func` 的“绑定的（bound）变体”，它绑定了上下文 `this` 和前几个参数（如果给定了）。
```suggestion
方法 `func.bind(context, ...args)` 返回函数 `func` 的“绑定的（bound）变体”，它绑定了上下文 `this` 和 `...args` 参数。
```

这里感觉没必要直译，就按参数表示意思更好理解一点

2023-05-21 15:33 UTC, liuchengwucn commented
/done

2023-05-21 15:44 UTC, songhn233 approved these changes
LGTM

2023-05-23 16:28 UTC, merged