语句优化
javascript-tutorial/zh.javascript.info pull request #1161
Opened 2023-06-27 02:49 UTC by ichiyouda

3. …… if we had ignored calls,  感觉这句译为「如果我们有被忽略的调用」，读起来更好理解一些，希望不是错译。

**目标章节**：1-js/06-advanced-functions/09-call-apply-decorators/04-throttle

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/ec84c3f8d8adad98f20b45ff4fb1a02b3722677e

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
solution.md | a23882d | 无

2023-06-27 02:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1161) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1161) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1161) it.</sub>

2023-06-27 15:16 UTC, songhn233 requested changes

2023-06-27 15:16 UTC, songhn233 commented on 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
> +3. 经过 `ms` 毫秒后，`setTimeout`中的函数被触发。冷却状态被移除（`isThrottled = false`），如果我们有被忽略（return）的调用，将使用最后保存的参数和上下文运行 `wrapper`。
```suggestion
3. 经过 `ms` 毫秒后，`setTimeout`中的函数被触发。冷却状态被移除（`isThrottled = false`），如果存在被忽略的调用，将使用最后一次调用保存的参数和上下文运行 `wrapper`。
```

2023-06-27 15:16 UTC, songhn233 commented on 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
> +第 3 步运行的不是 `func`，而是 `wrapper`，因为我们不仅需要执行 `func`，还需要再次进入冷却状态并设置延时以重置节流。
```suggestion
第 3 步运行的不是 `func`，而是 `wrapper`，因为我们不仅需要执行 `func`，还需要再次进入冷却状态并设置 `setTimeout` 以重置节流。
```

2023-06-27 15:22 UTC, songhn233 commented
Hey @ichiyouda. Thanks for your contribution. I've left some minor  changes to fix, other than that the PR looks good to me!

2023-06-28 00:41 UTC, ichiyouda commented on 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
> +3. 经过 `ms` 毫秒后，`setTimeout`中的函数被触发。冷却状态被移除（`isThrottled = false`），如果我们有被忽略（return）的调用，将使用最后保存的参数和上下文运行 `wrapper`。
哇！读起来舒服多了

2023-06-28 01:10 UTC, ichiyouda commented
/done

2023-06-28 01:25 UTC, ichiyouda commented
> 1. Please make the requested changes.  
> ……
> 2. Add more commits by pushing to the master branch on ichiyouda/zh.javascript.info. 

呜呜，对 Github 不太熟悉。改 PR 我只需要按照第二条的提示做就 Okay 了吧 😌

2023-07-02 11:46 UTC, leviding commented on 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
> +2. 在冷却状态下，所有调用都被保存在 `savedArgs/savedThis` 中。请注意，上下文（this）和参数（arguments）都很重要，应该被保存下来。我们同时需要它们来重现调用。
```suggestion
2. 在冷却状态下，所有调用都被保存在 `savedArgs/savedThis` 中。请注意，上下文（this）和参数（arguments）都很重要，应该被保存下来。我们需要它们来重现调用。
```

2023-07-02 11:47 UTC, leviding commented on 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
> +3. 经过 `ms` 毫秒后，`setTimeout`中的函数被触发。冷却状态被移除（`isThrottled = false`），如果存在被忽略的调用，将使用最后保存的参数和上下文运行 `wrapper`。
```suggestion
3. 经过 `ms` 毫秒后，`setTimeout`中的函数被触发。冷却状态被移除（`isThrottled = false`），如果存在被忽略的调用，将使用最后一次调用保存的参数和上下文运行 `wrapper`。
```

2023-07-02 11:48 UTC, leviding commented on 1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
> +第 3 步运行的不是 `func`，而是 `wrapper`，因为我们不仅需要运行 `func`，还需要再次进入冷却状态并设置`setTimeout`以重置节流。
```suggestion
第 3 步运行的不是 `func`，而是 `wrapper`，因为我们不仅需要执行 `func`，还需要再次进入冷却状态并设置 `setTimeout` 以重置节流。
```

2023-07-02 11:50 UTC, leviding approved these changes

2023-07-02 11:51 UTC, merged

2023-07-02 11:51 UTC, leviding commented
Thanks all!