fix：属性结尾应有逗号
javascript-tutorial/zh.javascript.info pull request #1222
Opened 2024-09-18 12:22 UTC by HeimaoLST

**目标章节**：1-js\04-object-basics\01-object\5-sum-object

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/b258d7d5b635c88228f7556e14fbe5e5ca7f736d

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
solution.md | 无 | 修改部分错误
task.md | 无 | 修改部分错误

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2024-09-18 12:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1222) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=1222) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=1222) it.</sub>

2024-09-18 12:23 UTC, xuesongde commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2024-10-05 14:47 UTC, songhn233 requested changes

2024-10-05 14:47 UTC, songhn233 commented on 1-js/04-object-basics/01-object/5-sum-object/task.md
> +  Pete: 130,
对象属性的尾逗号应该只是一个风格问题，这里感觉可以保留

2024-11-03 15:32 UTC, leviding commented
谢谢参与贡献，这只是一种代码风格，所以暂时保持

2024-11-03 15:32 UTC, closed without merging