Update article.md
javascript-tutorial/zh.javascript.info pull request #809
Opened 2020-07-29 14:41 UTC by chhhhhhq

**目标章节**：例如 1-js/01-getting-started/1-intro

**当前上游最新 commit**：此处填写本项目英文版 https://github.com/javascript-tutorial/en.javascript.info 的最新 commit，例如 https://github.com/javascript-tutorial/zh.javascript.info/commit/b03ca00a992a73aaf213970e71f74ac1c04def33

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | a23882d | 修改部分错误

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2020-08-08 09:07 UTC, bemself commented on 1-js/05-data-types/05-array-methods/article.md
> +  - `splice(index, deleteCount, ...items)` —— 从 `index` 开始删除 `deleteCount` 个元素，并在当前位置插入 `items`。
@chhhhhhq  感谢提交~

参考最新的英文
[en.javascript.info/article.md at master · javascript-tutorial/en.javascript.info](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/05-data-types/05-array-methods/article.md):

> - `splice(pos, deleteCount, ...items)` -- at index `pos` delete `deleteCount` elements and insert `items`.

个人建议和英文保持一致, 依然用 pos 作为参数, 修改后面的中文解释部分的翻译, 您觉得如何?

2020-08-11 06:45 UTC, chhhhhhq commented on 1-js/05-data-types/05-array-methods/article.md
> +  - `splice(index, deleteCount, ...items)` —— 从 `index` 开始删除 `deleteCount` 个元素，并在当前位置插入 `items`。
嗯嗯,我觉得您的改动更好些

2020-09-05 12:50 UTC, bemself requested changes

2020-09-05 12:50 UTC, bemself commented on 1-js/05-data-types/05-array-methods/article.md
> +  - `splice(index, deleteCount, ...items)` —— 从 `index` 开始删除 `deleteCount` 个元素，并在当前位置插入 `items`。
```suggestion
  - `splice(pos, deleteCount, ...items)` —— 从 `pos` 开始删除 `deleteCount` 个元素，并插入 `items`。
```

2020-09-05 12:50 UTC, bemself commented on 1-js/05-data-types/05-array-methods/article.md
> +  - `splice(index, deleteCount, ...items)` —— 从 `index` 开始删除 `deleteCount` 个元素，并在当前位置插入 `items`。
@chhhhhhq 我写了下建议的修改，您看下？

2020-09-08 01:21 UTC, MartinsYong approved these changes

2020-09-21 08:19 UTC, leviding approved these changes
LGTM.

2020-09-21 08:20 UTC, merged