add translation of 1-js/99-js-misc/04-reference-type
javascript-tutorial/zh.javascript.info pull request #810
Opened 2020-08-03 07:12 UTC by enrilchow

**目标章节**：1-js/99-js-misc/04-reference-type

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/b057341f6c90291e0b7a6f78fcf62effa03e4145#diff-b7075ff31f2598ce17999f70d3ab3fee

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 添加翻译

2020-08-24 08:20 UTC, enrilchow commented
/done

2020-09-05 03:09 UTC, MartinsYong requested changes
这里有个小问题

2020-09-05 03:09 UTC, MartinsYong commented on 1-js/99-js-misc/04-reference-type/article.md
> +Reference Type 是一个 ECMA 标准内部用于规范而使用的类型（specification type）。我们不能直接使用它，但它被 JavaScript 在执行引擎内部使用。（**注意：它并非我们通常所指的引用类型 —— reference type，而仅是 ECMA 标准中的一个命名，好比海燕与台风“海燕”之间并无直接联系**）
```suggestion
Reference Type 是一个 ECMA 标准内部用于规范而使用的类型（specification type）。我们不能直接使用它，但它被 JavaScript 在执行引擎内部使用。（**译注：它并非我们通常所指的引用类型 —— reference type，而仅是 ECMA 标准中的一个命名，好比海燕与台风“海燕”之间并无直接联系**）
```

2020-09-05 03:09 UTC, MartinsYong commented on 1-js/99-js-misc/04-reference-type/article.md
> +Reference Type 是一个 ECMA 标准内部用于规范而使用的类型（specification type）。我们不能直接使用它，但它被 JavaScript 在执行引擎内部使用。（**注意：它并非我们通常所指的引用类型 —— reference type，而仅是 ECMA 标准中的一个命名，好比海燕与台风“海燕”之间并无直接联系**）
额外添加的合理内容，请注明“译注”

2020-09-07 06:02 UTC, enrilchow commented
/done

2020-09-08 01:19 UTC, MartinsYong approved these changes

2020-09-22 02:33 UTC, leviding approved these changes
LGTM.

2020-09-22 02:33 UTC, merged

2020-09-22 02:33 UTC, leviding commented
感谢翻译和校对