translate some missing contents
javascript-tutorial/zh.javascript.info pull request #811
Opened 2020-08-03 23:07 UTC by zomb-676

**目标章节**:1-js/09-classes/01-class和1-js/09-classes/02-class-inheritance

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/da9849d61a9f4b9f0d86993baaf494c5b73d4edb#diff-619f8744f6687e607b8859843952d6b2和
https://github.com/javascript-tutorial/en.javascript.info/commit/26bf51af3e9a63b6f57b68f42fcc1656afc59663#diff-bab52830ec6d1a34780283a014963061

**本 PR 所做更改如下**:粗糙的翻译了下原本未翻译的内容

新增翻译未翻,无参考

2020-08-03 23:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=811) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=811) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=811) it.</sub>

2020-08-15 04:00 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +- 对于被派生类,在调用 `super()`后立刻加载。
```suggestion
- 对于派生类，在调用 `super()` 后立刻初始化。
```

2020-08-15 04:01 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +- 在基类被构造前加载(不继承任何类的那种)。
```suggestion
- 在基类（不继承任何类的那种）被构造前初始化。
```

2020-08-15 04:08 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +在我们这种情况下, `Rabbit`是被派生类,这里面没有 `constructor()`。正如先前所说,如果这里面只有一个空的构造器,里面只有`super(...args)`,那么这是相同的。
```suggestion
在例子中，`Rabbit` 是派生类，里面没有 `constructor()`。正如先前所说，这相当于一个里面只有`super(...args)`的空构造器。
```

2020-08-15 04:09 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +这属性和方法之间微妙的区别只特定于JavaScript。
```suggestion
这种字段与方法之间微妙的区别只特定于 JavaScript。
```

2020-08-15 04:12 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +幸运的是,这种行为仅在一个被重写的属性被父类构造器使用时显示出来。接下来它会发生什么就很难理解了,所以我们在这里解释它。
```suggestion
幸运的是，这种行为仅在一个被重写的字段被父类构造器使用时显现出来。接下来它会发生什么可能就很难理解了，所以我们要在这里对此行为进行解释。
```

2020-08-15 04:13 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +如果它成为了一个问题,我们可以通过使用方法或者getter/setter而不是属性来修复它。
```suggestion
如果出问题了，我们可以通过使用方法或者 getter/setter 而不是类字段来修复。
```

2020-08-15 04:18 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +所以, `new Rabbit()`调用了 `super()`因此它执行了父类构造器,并且(根据类的派生规则)只有在此之后,他的类属性才被加载。在父类构造器被执行的时候,这是还没用类属性`Rabbit`,这就是为什么`Animal`属性被使用了。
```suggestion
所以，`new Rabbit()` 调用了 `super()`，因此它执行了父类构造器，并且（根据派生类规则）只有在此之后，它的类字段才被初始化。在父类构造器被执行的时候，`Rabbit` 还没有自己的类字段，这就是为什么`Animal` 类字段被使用了。
```

2020-08-15 04:25 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +这个提示假设你或许在其他编程语言中有一定的关于类的经验。
```suggestion
这个注意要点假设你或许在其他编程语言中有一定的关于类的经验。
```

2020-08-30 03:28 UTC, MartinsYong commented
@zomb-676 有一些修改建议请看一下，谢谢~

2020-09-04 13:40 UTC, zomb-676 reviewed
感谢修正

2020-09-04 14:01 UTC, zomb-676 commented
> @zomb-676 有一些修改建议请看一下，谢谢~

不是我想刷commit,有办法一次性同意所有commit suggestion么)
/done

2020-09-05 02:52 UTC, MartinsYong commented
> > @zomb-676 有一些修改建议请看一下，谢谢~
> 
> 不是我想刷commit,有办法一次性同意所有commit suggestion么)
> /done

有个 batch 的功能按钮可以点击，然后都需要的 suggestion 都点完之后，然后就点一起 commit 就行。下次可以留意一下~

2020-09-05 02:53 UTC, MartinsYong commented
@zomb-676 
还有第 375、377 行需要再看一下~

2020-09-09 05:39 UTC, zomb-676 commented
/done

2020-09-11 12:56 UTC, MartinsYong requested changes
还有第 336、341 行注释需要翻译，那里我添加不了 suggestion

2020-09-11 12:56 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +在例子中，`Rabbit` 是派生类，里面没有 `constructor()`。正如先前所说，这相当于一个里面只有`super(...args)`的空构造器。
```suggestion
在例子中，`Rabbit` 是派生类，里面没有 `constructor()`。正如先前所说，这相当于一个里面只有 `super(...args)` 的空构造器。
```

2020-09-11 12:56 UTC, MartinsYong commented on 1-js/09-classes/02-class-inheritance/article.md
> +所以，`new Rabbit()` 调用了 `super()`，因此它执行了父类构造器，并且（根据派生类规则）只有在此之后，它的类字段才被初始化。在父类构造器被执行的时候，`Rabbit` 还没有自己的类字段，这就是为什么`Animal` 类字段被使用了。
```suggestion
所以，`new Rabbit()` 调用了 `super()`，因此它执行了父类构造器，并且（根据派生类规则）只有在此之后，它的类字段才被初始化。在父类构造器被执行的时候，`Rabbit` 还没有自己的类字段，这就是为什么 `Animal` 类字段被使用了。
```

2020-09-22 08:44 UTC, leviding approved these changes
LGTM.

2020-09-22 08:50 UTC, merged

2020-09-22 08:50 UTC, leviding commented
已经合并，感谢各位的翻译和校对 ❤️