Catastrophic backtracking
javascript-tutorial/zh.javascript.info pull request #820
Opened 2020-08-31 10:43 UTC by Isildur46

**目标章节**：9-regular-expressions/15-regexp-catastrophic-backtracking

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/32e20fc97c59262b116862d3a9ca7c2dd961cb3f#diff-daa73ffcb00f33284c228961daab9209

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | https://github.com/javascript-tutorial/en.javascript.info/commit/32e20fc97c59262b116862d3a9ca7c2dd961cb3f#diff-daa73ffcb00f33284c228961daab9209 | 首次翻译

2020-09-05 13:17 UTC, bemself requested changes
@Isildur46 感谢翻译！一点格式上的小问题，请再查看一下~

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +不幸的是，这没用：如果我们用 `pattern:\d+?` 去替代 `pattern:\d+` ，它还是会挂起。排列组合的顺序会变化，但是总数不变。
```suggestion
不幸的是，这没用：如果我们用 `pattern:\d+?` 去替代 `pattern:\d+`，它还是会挂起。排列组合的顺序会变化，但是总数不变。
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +有 2 种可以帮助解决问题思路。
```suggestion
主要有 2 种解决方法。
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +现在星号 `pattern:*` 跟在 `pattern:\w+\s` 后面，而不是 `pattern:\w+\s?` 后面。 这意味着它无法匹配一个拥有多个连续单字字符串 `pattern:\w+` 的单词，也就省下了原本去尝试这些排列组合的时间。
```suggestion
现在星号 `pattern:*` 跟在 `pattern:\w+\s` 后面，而不是 `pattern:\w+\s?` 后面。这意味着它无法匹配一个拥有多个连续单字字符串 `pattern:\w+` 的单词，也就省下了原本去尝试这些排列组合的时间。
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +举个例子，之前那个模式 `pattern:(\w+\s?)*` 可能以两个 `pattern:\w+` 的方式来匹配单词 `subject:string` ：
```suggestion
举个例子，之前那个模式 `pattern:(\w+\s?)*` 可能以两个 `pattern:\w+` 的方式来匹配单词 `subject:string`：
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +之前那个模式，由于存在可选的 `pattern:\s` ，它允许 `pattern:\w+`，`pattern:\w+\s`，`pattern:\w+\w+` 等等的变体形式。
```suggestion
之前那个模式，由于存在可选的 `pattern:\s`，它允许 `pattern:\w+`、`pattern:\w+\s` 和 `pattern:\w+\w+` 等等的变体形式。
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +比如，正则 `pattern:(\d+)*$` 中 `pattern:+` 对于我们人类来说很明显不应去回溯，就算我们用两个独立的 `pattern:\d+\d+` 去替换一个 `pattern:\d+`， 也是根本没作用的：
```suggestion
比如，正则 `pattern:(\d+)*$` 中 `pattern:+` 对于我们人类来说很明显不应去回溯，就算我们用两个独立的 `pattern:\d+\d+` 去替换一个 `pattern:\d+`，也是根本没作用的：
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +例如，在单词 `subject:JavaScript` 不仅可以匹配 `match:Java`，而且可以忽略 `match:Script` ，匹配模式的其余部分。
```suggestion
例如，在单词 `subject:JavaScript` 中不仅可以匹配 `match:Java`，而且可以忽略 `match:Script`，匹配模式的其余部分。
```

2020-09-05 13:17 UTC, bemself commented on 9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
> +这里我们用 `pattern:\2` 代替 `pattern:\1`，因为这里附加了额外的外部括号。为了防止数字产生混淆，，我们可以给括号命名，例如 `pattern:(?<word>\w+)`。
```suggestion
这里我们用 `pattern:\2` 代替 `pattern:\1`，因为这里附加了额外的外部括号。为了防止数字产生混淆，我们可以给括号命名，例如 `pattern:(?<word>\w+)`。
```

2020-09-07 05:53 UTC, Isildur46 commented
格式已修正，更新了 PR。 @bemself

2020-09-07 05:55 UTC, Isildur46 commented
/done

2020-09-19 06:23 UTC, Isildur46 commented
/done
已修正翻译

2020-11-16 07:16 UTC, merged

2020-11-16 07:17 UTC, leviding commented
感谢翻译和校对 👍