Translate: 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce
javascript-tutorial/zh.javascript.info pull request #843
Opened 2020-10-20 04:47 UTC by Ninglo

**目标章节**：例如 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce

**当前上游最新 commit**：https://github.com/javascript-tutorial/en.javascript.info/commit/d6e88647b42992f204f57401160ebae92b358c0d

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
task.md | d6e8864| 英译中
solution.md | d6e8864 | 英译中

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2020-10-20 04:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=843) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=843) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=843) it.</sub>

2020-11-04 11:47 UTC, MartinsYong requested changes
校对完成~感谢您的翻译

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +在 0ms，200ms 和 500ms 时调用这个包装函数，之后不在调用，那么真正的`f`将于 1500ms 时被调用一次。它是在 1000ms 冷静期中的最后一次调用。
```suggestion
如果在 0ms、200ms 和 500ms 时调用这个包装函数，之后不再调用，那么真正的 `f` 只会在 1500ms 时被调用一次。也就是：从最后一次调用开始的 1000ms 冷却期之后。
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +...并且它会携带最后一次调用的所有请求，其他的请求将被忽略。
```suggestion
……并且它会获取到最后一次调用的所有参数，其他请求的参数将被忽略。
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +# 防抖装饰者
```suggestion
# 防抖装饰器
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +以下是它的代码 (使用 [Lodash library](https://lodash.com/docs/4.17.15#debounce) 的防抖装饰者):
```suggestion
以下是它的代码 (使用来自 [Lodash library](https://lodash.com/docs/4.17.15#debounce) 的防抖装饰器):
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +// 防抖函数从最后一次函数调用以后等待 1000ms，然后运行: alert("c")
```suggestion
// 防抖函数从最后一次函数调用以后等待 1000ms，然后运行：alert("c")
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +没必要为了一个字符的输入发送请求。相反，我们可以稍等片刻，然后发送整个结果。
```suggestion
没必要为了每一个字符的输入而发送请求。相反，我们可以稍等片刻，然后发送整个结果。
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +在浏览器中，我们可以设置一个事件处理程序 -- 一个每次输入内容发送变化都会调用的函数。通常，监听所有键盘输入的事件处理程序会被调用的非常频繁。但是如果我们为这个程序做 1000ms 的 `debounce` 处理，它就只会被调用一次，发送 1000ms 内最后一次输入后的数据。
```suggestion
在浏览器中，我们可以设置一个事件处理程序 —— 一个每次输入内容发送变化都会调用的函数。通常，监听所有键盘输入的事件处理程序会被调用的非常频繁。但是如果我们为这个程序做 1000ms 的 `debounce` 处理，它就只会被调用一次，在最后一次输入后的 1000ms 后。
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +因此，`debounce` 是一个处理一串事件的好方法: 无论是一串键盘输入，鼠标移动还是其他类似的东西。
```suggestion
因此，`debounce` 是一个处理一连串事件的好方法：无论是一串键盘输入，鼠标移动还是其他类似的事件。
```

2020-11-04 11:47 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +任务是实现一个 `debounce` 装饰者。
```suggestion
任务是实现一个 `debounce` 装饰器。
```

2020-11-05 09:57 UTC, JaykeyGuo commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +...并且它会携带最后一次调用的所有请求，其他的请求将被忽略。
“其他请求的参数”建议改成“其他调用的参数”

2020-11-05 10:00 UTC, JaykeyGuo requested changes
waiting for your edit

2020-11-05 15:10 UTC, Ninglo commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +# 防抖装饰者
这里我也认为是装饰器合适, 但是可以看下 https://zh.javascript.info/call-apply-decorators 里面, 都翻译为了装饰者, 所以我觉得还是顺着官方的翻译比较好.

2020-11-07 04:48 UTC, MartinsYong commented on 1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
> +# 防抖装饰者
好的~没问题
@Ninglo

2020-11-07 08:44 UTC, Ninglo commented
/done

2020-11-09 05:33 UTC, MartinsYong approved these changes

2020-11-17 13:15 UTC, leviding commented
感谢翻译，我对内容进行了一些优化。

1. 注意细节格式
2. 注意调整语序，使其更符合国人的阅读习惯
3. 装饰者统一改为装饰器，我随后将修改本教程所有本词的翻译

感谢两位。

2020-11-17 13:15 UTC, merged