8-web-components/2-custom-elements
javascript-tutorial/zh.javascript.info pull request #845
Opened 2020-11-05 09:43 UTC by JaykeyGuo

**目标章节**：8-web-components/2-custom-elements/article.md

**当前上游最新 commit**：无

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | 无 | 更改中文错别字

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2020-11-05 09:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=845) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=845) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=845) it.</sub>

2020-11-07 05:47 UTC, MartinsYong approved these changes

2020-11-08 01:00 UTC, bemself requested changes
一点小改动:-)

2020-11-08 01:00 UTC, bemself commented on 8-web-components/2-custom-elements/article.md
> +    // 当上面数组中的属性发上变化的时候，这个方法会被调用
```suggestion
    // 当上面数组中的属性发生变化的时候，这个方法会被调用
```

2020-11-16 07:08 UTC, leviding approved these changes
Thanks a lot!

2020-11-16 07:09 UTC, merged