UPD: update to 2020-10-15
javascript-tutorial/zh.javascript.info pull request #848
Opened 2020-11-07 05:18 UTC by leviding

Update to 2020-10-15 from upstream.

2020-11-08 09:31 UTC, MartinsYong requested changes
这个有点疑问，可能是原文问题？

2020-11-08 09:31 UTC, MartinsYong commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +## 异步 generator
原文是：`## Async generators (finally)`
🧐

2020-11-08 10:24 UTC, leviding commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +## 异步 generator
@MartinsYong 这里我不知道原文的 finally 是什么意思，就删了。这里可能补回去比较好？

2020-11-11 00:52 UTC, MartinsYong requested changes

2020-11-11 00:52 UTC, MartinsYong commented on 2-ui/3-event-details/6-pointer-events/article.md
> +经过上述操作，事件将会按照我们预期的方式触发，浏览器不会劫持拖放过程，也不会产生 `pointercancel` 事件。
```suggestion
经过上述操作，事件将会按照我们预期的方式触发，浏览器不会劫持拖放过程，也不会触发 `pointercancel` 事件。
```

2020-11-11 00:53 UTC, MartinsYong commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +## 异步 generator
补回去吧，虽然我也不太清楚啥意思

2020-11-14 04:57 UTC, MartinsYong commented on 2-ui/5-loading/02-script-async-defer/article.md
> +在这个例子中，`loadScript(src)` 函数添加了一个脚本，并将 `async` 设置为了 `false`。
这里原文应该需要加个 `below`：
`In the example below`

2020-11-14 05:21 UTC, leviding commented
辛苦啦，目前所有意见均已更改完毕，等待进一步意见～

2020-11-14 06:57 UTC, MartinsYong requested changes
还有点小问题

2020-11-14 06:57 UTC, MartinsYong commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
>  这些方法可以一起使用，如下所示：
239 行末补上：`在这样的情况下，我们使用`

2020-11-14 06:57 UTC, MartinsYong commented on 5-network/04-fetch-abort/article.md
> +`AbortController` 是可伸缩的，它允许一次取消多个 fetche。
```suggestion
`AbortController` 是可伸缩的，它允许一次取消多个 fetch。
```

2020-11-15 03:38 UTC, leviding commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
>  这些方法可以一起使用，如下所示：
DONE

2020-11-15 03:39 UTC, merged

2020-11-15 03:39 UTC, leviding commented
DONE，辛苦啦～