UPD: update to 2020-11-15
javascript-tutorial/zh.javascript.info pull request #852
Opened 2020-11-17 03:21 UTC by leviding

Update translation to 2020-11-15 from upstream.

2020-11-17 13:39 UTC, leviding commented
Related to https://github.com/javascript-tutorial/zh.javascript.info/pull/851

2020-11-21 02:58 UTC, MartinsYong requested changes
校对完成 @leviding

2020-11-21 02:58 UTC, MartinsYong commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +当我们从 `object` 中读取一个缺失的属性时，JavaScript 会自动从原型中获取该属性。在编程中，这种行为被称为“原型继承”。很快，我们将通过很多示例来学习此类继承，以及基于该继承的更炫酷的语言功能。
```suggestion
当我们从 `object` 中读取一个缺失的属性时，JavaScript 会自动从原型中获取该属性。在编程中，这种行为被称为“原型继承”。很快，我们将通过很多示例来学习此类继承，以及基于此类继承的更炫酷的语言功能。
```

2020-11-21 02:58 UTC, MartinsYong commented on 1-js/11-async/05-promise-api/article.md
> +  const rejectHandler = reason => ({ status: 'rejected', reason });
这一整段行数没对齐

2020-11-21 02:58 UTC, MartinsYong commented on 1-js/11-async/08-async-await/03-async-from-regular/task.md
> +  // ...这里你应该怎么写？
```suggestion
  // ……这里你应该怎么写？
```

2020-11-21 02:58 UTC, MartinsYong commented on 1-js/13-modules/02-import-export/article.md
> +想象一下，我们正在编写一个 "package"：一个包含大量模块的文件夹，其中一些功能是导出到外部的（像 NPM 这样的工具允许我们发布和分发这样的 package，但我们不是必须使用它们），并且其中一些模块仅仅是供其他 package 中的模块内部使用的 "helpers"。
```suggestion
想象一下，我们正在编写一个 "package"：一个包含大量模块的文件夹，其中一些功能是导出到外部的（像 NPM 这样的工具允许我们发布和分发这样的 package，但我们不必使用它们），并且其中一些模块仅仅是供其他 package 中的模块内部使用的 "helpers"。
```

2020-11-21 06:25 UTC, leviding commented on 1-js/11-async/05-promise-api/article.md
> +  const rejectHandler = reason => ({ status: 'rejected', reason });
Solved.

2020-11-21 06:26 UTC, leviding commented on 1-js/13-modules/02-import-export/article.md
> +想象一下，我们正在编写一个 "package"：一个包含大量模块的文件夹，其中一些功能是导出到外部的（像 NPM 这样的工具允许我们发布和分发这样的 package，但我们不是必须使用它们），并且其中一些模块仅仅是供其他 package 中的模块内部使用的 "helpers"。
这里原文： but we don't have to use them

是不是【不是必须】更好，因为【不必】表示的是不需要或用不着

2020-11-21 07:11 UTC, MartinsYong commented on 1-js/13-modules/02-import-export/article.md
> +想象一下，我们正在编写一个 "package"：一个包含大量模块的文件夹，其中一些功能是导出到外部的（像 NPM 这样的工具允许我们发布和分发这样的 package，但我们不是必须使用它们），并且其中一些模块仅仅是供其他 package 中的模块内部使用的 "helpers"。
嗯嗯，我理解你的意思。
想到俩更佳的表达：
1. `但我们不是必须要去使用它们`
2. `但我们并不一定要使用它们`

2020-11-21 08:35 UTC, merged

2020-11-21 08:38 UTC, leviding commented
@MartinsYong 感谢