FIX: translation errors
javascript-tutorial/zh.javascript.info pull request #967
Opened 2021-11-15 15:53 UTC by 3Alan

这里备注“建议”的目的不知是何，而且continue是不能与三元表达式一起使用的，这样翻译很容易给阅读者造成疑惑。
根据英文版 https://javascript.info/while-for#continue 的意思来看也确实不是这样，所以这应该是一个翻译错误。

**目标章节**：例如 1-js/01-getting-started/1-intro

**当前上游最新 commit**：此处填写本项目英文版 https://github.com/javascript-tutorial/en.javascript.info 的最新 commit，例如 https://github.com/javascript-tutorial/zh.javascript.info/commit/b03ca00a992a73aaf213970e71f74ac1c04def33

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | a23882d | 修改部分错误

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2021-11-15 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=967) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=967) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=967) it.</sub>

2021-11-15 17:18 UTC, songhn233 commented
我觉得这里的（建议）是可以保留的。

因为这实际上类似表现力的差异，由于三目运算符 ? 不能使用 continue 和 break，所以在循环的场景下不能很方便的进行跳出操作。但是在很多场景中三目运算符 ? 确实能起到减少代码、逻辑清晰的作用。

这里的建议只是一个表达委婉的说法，? 本身使用还是很频繁的，所以没有必要做改动。

2021-11-15 17:18 UTC, songhn233 requested changes
这里的建议可以保留

2021-11-16 00:35 UTC, 3Alan commented
我之前的理解是这句话是对上面循环例子的解释（因为例子中是确切不能使用continue，所以就不存在“建议”这一说法）。你说的应该是跳出了例子，整体对if和?使用场景的解释（这种情况下加“建议”确实说的过去）吧？

2021-11-17 14:33 UTC, songhn233 commented
> 我之前的理解是这句话是对上面循环例子的解释（因为例子中是确切不能使用continue，所以就不存在“建议”这一说法）。你说的应该是跳出了例子，整体对if和?使用场景的解释（这种情况下加“建议”确实说的过去）吧？

这里提到了「另一个原因」，所以和上文最开始提到 ? 时的 [‘?’ 的非常规使用](https://zh.javascript.info/ifelse#de-fei-chang-gui-shi-yong) 是对应的。

而且前一句明确提到了「代码会停止运行，并显示有语法错误」。后面这句话只是总结性质的，应该不构成歧义。

2021-11-17 15:43 UTC, closed without merging

2021-11-17 15:44 UTC, 3Alan commented
明白了，感谢解答了我的疑惑