Translate tasks in  9-regular-expressions/11-regexp-groups
javascript-tutorial/zh.javascript.info pull request #969
Opened 2021-11-23 04:29 UTC by zzy2008

**目标章节**：例如 9-regular-expressions/11-regexp-groups/

**当前上游最新 commit**：无

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
01-test-mac/task.md | 无 | 翻译
01-test-mac/solution.md | 无 | 翻译
02-find-webcolor-3-or-6/task.md | 无 | 翻译
02-find-webcolor-3-or-6/solution.md | 无 | 翻译
03-find-decimal-numbers/task.md | 无 | 翻译
03-find-decimal-numbers/solution.md | 无 | 翻译
04-parse-expression/task.md | 无 | 翻译
04-parse-expression/solution.md | 无 | 翻译

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2021-12-19 07:37 UTC, bemself requested changes
感谢翻译！

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
> +一个两位的十六进制匹配串是`pattern:[0-9a-f]{2}`（假设已设置标志`pattern:i`）。
```suggestion
一个两位的十六进制匹配串是 `pattern:[0-9a-f]{2}`（假设已设置标志 `pattern:i`）。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
> +我们需要匹配数字对 `NN`，然后再重复匹配5次 `:NN`；
```suggestion
我们需要匹配数字对 `NN`，然后再重复 5 次 `:NN`（匹配更多数字）；
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
> +alert( regexp.test('01:32:54:67:89') ); // false (只有5个数字对，应为6个)
```suggestion
alert( regexp.test('01:32:54:67:89') ); // false（只有 5 个数字对，应为 6 个）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
> +alert( regexp.test('01:32:54:67:89:ZZ') ) // false (最后的数字对为ZZ)
```suggestion
alert( regexp.test('01:32:54:67:89:ZZ') ) // false（最后是字符 ZZ）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
> +alert( regexp.test('0132546789AB') ); // false (没有冒号)
```suggestion
alert( regexp.test('0132546789AB') ); // false（没有冒号）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/task.md
> +网络接口的 [MAC-address](https://en.wikipedia.org/wiki/MAC_address) 包含由冒号分隔的6个两位十六进制数字对。
```suggestion
网络接口的 [MAC 地址](https://en.wikipedia.org/wiki/MAC_address) 包含由冒号分隔的 6 个两位十六进制数字对。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/task.md
> +创建一个正则表达式语句来检查给出的字符串是否为 MAC-address 。
```suggestion
创建一个正则表达式语句来检查给出的字符串是否为 MAC 地址。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/task.md
> +alert( regexp.test('0132546789AB') ); // false (没有冒号)
```suggestion
alert( regexp.test('0132546789AB') ); // false（没有冒号）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/task.md
> +alert( regexp.test('01:32:54:67:89') ); // false (只有5个数字对，应为6个)
```suggestion
alert( regexp.test('01:32:54:67:89') ); // false（只有 5 个数字对，应为 6 个）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/01-test-mac/task.md
> +alert( regexp.test('01:32:54:67:89:ZZ') ) // false (最后的数字对为ZZ)
```suggestion
alert( regexp.test('01:32:54:67:89:ZZ') ) // false（最后是字符 ZZ）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
> +查找3位数字颜色 `#abc` 的正则表达式：`pattern:/#[a-f0-9]{3}/i`。
```suggestion
查找 3 位长的颜色 `#abc` 的正则表达式：`pattern:/#[a-f0-9]{3}/i`。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
> +我们可以再添加3位可选的十六进制数字。这样刚好，因为要匹配的颜色编码由3位或6位组成。
```suggestion
我们可以再添加 3 位可选的十六进制数字。这样刚好，因为要匹配的颜色编码由 3 位或 6 位组成。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
> +这里使用量词 `pattern:{1,2}`，所以正则表达式为 `pattern:/#([a-f0-9]{3}){1,2}/i`。
```suggestion
我们用使用量词 `pattern:{1,2}` 来实现，所以正则表达式为 `pattern:/#([a-f0-9]{3}){1,2}/i`。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
> +这里将模式 `pattern:[a-f0-9]{3}` 包裹在字符串中以应用量词 `pattern:{1,2}`。
```suggestion
这里将模式 `pattern:[a-f0-9]{3}` 用括号括起来，在其外面应用量词 `pattern:{1,2}`。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/task.md
> +# 找出行如 #abc 或 #abcdef 的颜色编码
```suggestion
# 找出形如 #abc 或 #abcdef 的颜色编码
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/task.md
> +P.S. 必须是3位或6位十六进制数字。不应该匹配4位数字，比如 `#abcd`。
```suggestion
P.S. 必须是 3 位或 6 位十六进制数字。不应该匹配 4 位数字，比如 `#abcd`。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/solution.md
> +一个带有小数部分的正数的模式为： `pattern:\d+(\.\d+)?`。
```suggestion
一个带有可选小数部分的正数的模式为：`pattern:\d+(\.\d+)?`。（参考前一任务）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/task.md
> +创建一个正则表达式找出所有的十进制数字，包括整数，浮点数和负数。
```suggestion
创建一个正则表达式找出所有的十进制数字，包括整数、浮点数和负数。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +表达式的模式为 `pattern:[-+*/]`。连字符 `pattern:-` 在方括号内的第一位，因为放在中间可能表示字符范围，而我们只想表示一个字符 `-`。
```suggestion
运算操作符的模式为 `pattern:[-+*/]`。连字符 `pattern:-` 在方括号内的第一位，因为放在中间可能表示字符范围，而我们只想表示一个字符 `-`。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +我们需要一个数字，一个操作符然后另一个数字。其间有可选的空格。
```suggestion
我们需要一个数字、一个操作符以及另一个数字。其间可能有空格。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +整体的正则表达式为： `pattern:-?\d+(\.\d+)?\s*[-+*/]\s*-?\d+(\.\d+)?`。
```suggestion
完整的正则表达式为： `pattern:-?\d+(\.\d+)?\s*[-+*/]\s*-?\d+(\.\d+)?`。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +它包含 3 部分，每部分之前有 `pattern:\s*`：
```suggestion
它包含 3 部分，彼此之间用 `pattern:\s*` 间隔：
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +- `result[5] == undefined` (fifth group `(\.\d+)?` -- 第二个数字的小数部分是缺失的，所以这里是 undefined)
```suggestion
- `result[5] == undefined`（第五组 `(\.\d+)?` -- 第二个数字的小数部分是缺失的，所以这里是 undefined）
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +- `result[0] == "1.2 + 12"` (完全匹配)
这里的括号最好换成中文的括号，以下同

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
> +包含小数部分的组（第2和第4个）`pattern:(.\d+)` 可以通过在开头添加 `pattern:?:` 来排除。
```suggestion
包含小数部分的组（第 2 和第 4 个）`pattern:(.\d+)` 可以通过在开头 `pattern:(?:\.\d+)?` 添加 `pattern:?:` 来排除。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/task.md
> +操作符是 `"+"`, `"-"`, `"*"`， `"/"` 其中之一。
```suggestion
操作符是 `"+"`、`"-"`、`"*"` 和 `"/"` 其中之一。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/task.md
> +在开头，中间或结尾可能包含额外的空格。
```suggestion
在开头、中间或结尾可能包含额外的空格。
```

2021-12-19 07:37 UTC, bemself commented on 9-regular-expressions/11-regexp-groups/04-parse-expression/task.md
> +创建一个函数 `parse(expr)`，以一个算术表达式作为参数，返回包含3项的数组：
```suggestion
创建一个函数 `parse(expr)`，以一个算术表达式作为参数，返回包含 3 个元素的数组：
```

2021-12-19 08:43 UTC, zzy2008 reviewed
/done

2021-12-19 08:47 UTC, zzy2008 reviewed
/done

2021-12-21 11:26 UTC, bemself approved these changes

2022-02-06 02:36 UTC, merged