翻译9-regular-expressions/14-regexp-lookahead-lookbehind 下的任务部分内容
javascript-tutorial/zh.javascript.info pull request #974
Opened 2021-11-29 01:35 UTC by xdsnet

**目标章节**：例如 1-js/01-getting-started/1-intro

**当前上游最新 commit**：此处填写本项目英文版 https://github.com/javascript-tutorial/en.javascript.info 的最新 commit，例如 https://github.com/javascript-tutorial/zh.javascript.info/commit/b03ca00a992a73aaf213970e71f74ac1c04def33

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | a23882d | 修改部分错误

> 注意，参考上游 commit 是指你所修改的文件，在英文仓库中同名文件的对应 commit，即你此次提交的修改的依据。如果本 PR 你只是提交一个文字或者语句优化，并非根据上游英文仓库的修改而提交的更新，则请填无。

2021-11-29 01:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=974) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=974) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=974) it.</sub>

2021-11-29 03:11 UTC, xdsnet commented
I have read the CLA Document and I hereby sign the CLA

2021-12-19 06:19 UTC, bemself requested changes
感谢翻译！

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/solution.md
> +我们可以通过在它前面加上否定的前瞻来排除不正确的情况: `表达式:(?<!-)\d+`.
另外，句号问题

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/solution.md
> +我们可以通过在它前面加上否定的前瞻来排除不正确的情况: `表达式:(?<!-)\d+`.
关于 negative lookahead 的翻译，建议全篇统一一下，参考第 15 行的 comment

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/task.md
> +创建一个正则表达式来找出所有的非负整数 (0也是非负整数)。
```suggestion
创建一个正则表达式来找出所有的非负整数（0 也是非负整数）。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +为了在`<body>`标记之后插入，我们必须首先找到它。我们可以使用正则表达式模式`<body.*？>`来实现这一点。
```suggestion
为了在 `<body>` 标记之后插入，我们必须首先找到它。我们可以使用正则表达式模式 `<body.*?>` 来实现这一点。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +在这个任务中，我们不需要修改`<body>`标记。我们只需要在它后面添加文本。
```suggestion
在这个任务中，我们不需要修改 `<body>` 标记。我们只需要在它后面添加文本。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +在替换字符串中，`$&`表示匹配本身，即源文本中与`<body.*？>`相对应的部分。它会被自身加上`<h1>Hello</h1>`替换。
```suggestion
在替换字符串中，`$&` 表示匹配本身，即源文本中与 `<body.*?>` 相对应的部分。它会被自身加上 `<h1>Hello</h1>` 替换。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +正如您所看到的，这个正则表达式中只有后瞻断言部分
```suggestion
正如您所看到的，这个正则表达式中只有后瞻断言部分。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +* 检查它之前是否有<body.*？>。
```suggestion
* 检查它之前是否有 <body.*?>。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +因此，它将紧接`<body.*？>`的“空行”替换为`<h1>Hello</h1>`。这样就在`<body>`之后插入了内容。
```suggestion
因此，它将紧接 `<body.*?>` 的“空行”替换为 `<h1>Hello</h1>`。这样就在 `<body>` 之后插入了内容。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
> +P.S. 正则式中单标记如`s` 和 `i` 也经常被使用，如: `/<body.*?>/si`. 这里 `s`标记使得 `.`可以匹配换行符，而`i` 标记表示大小写不敏感，即 `<body>` 和 `<BODY>`都可以被匹配。
```suggestion
另外，正则表达式中的标记如 `s` 和 `i` 也经常被使用，如: `/<body.*?>/si`。这里 `s` 标记使得 `.` 可以匹配换行符，而 `i` 标记表示大小写不敏感，即 `<body>` 和 `<BODY>` 都可以被匹配。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/task.md
> +我们有一个带有HTML文档的字符串。
```suggestion
我们有一个带有 HTML 文档的字符串。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/task.md
> +编写一个正则表达式，在`<body>`标记之后立即插入`<h1>Hello</h1>`。标记可能具有属性。
```suggestion
编写一个正则表达式，在 `<body>` 标记之后立即插入 `<h1>Hello</h1>`。标记可能具有属性。
```

2021-12-19 06:19 UTC, bemself commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/task.md
> +在此之后，`str`的值应为：
```suggestion
在此之后，`str` 的值应为：
```

2022-02-05 14:58 UTC, merged