docs: 更新运算符优先级
javascript-tutorial/zh.javascript.info pull request #991
Opened 2022-01-11 07:35 UTC by hankaibo

**目标章节**：1-js/02-first-steps/08-operators/article.md

**当前上游最新 commit**：无

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | a23882d | 更新优先级

2022-01-11 07:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=991) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh.javascript.info?pullRequest=991) before we can accept your contribution.<br/><hr/>**hankaibo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh.javascript.info?pullRequest=991) it.</sub>

2022-01-11 07:46 UTC, songhn233 requested changes
[上游](https://javascript.info/operators) 还没有同步，从 [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table) 看这个修改是正确的。

建议给原仓库先提一个 PR，然后我们这边同步。

2022-02-04 06:15 UTC, leviding commented
Related https://github.com/javascript-tutorial/en.javascript.info/pull/2853

2022-02-07 14:59 UTC, leviding approved these changes

2022-02-07 15:03 UTC, merged