fix: translation in 1-js/06-advanced-functions/03-closure/article.md
javascript-tutorial/zh.javascript.info pull request #994
Opened 2022-01-15 10:43 UTC by ZhaoTim

**目标章节**：1-js/06-advanced-functions/03-closure/

**当前上游最新 commit**：

**本 PR 所做更改如下：**

文件名 | 参考上游 commit | 更改（理由）
-|-|-
article.md | a23882d | 使其通顺

2022-01-15 12:00 UTC, songhn233 requested changes

2022-01-15 12:00 UTC, songhn233 commented on 1-js/06-advanced-functions/03-closure/article.md
> +当一个函数是在另一个函数中创建的时候，那么该函数就被称为“嵌套”的。
```suggestion
如果一个函数是在另一个函数中创建的，该函数就被称为“嵌套”的。
```

2022-01-15 12:43 UTC, songhn233 approved these changes

2022-01-15 12:47 UTC, ZhaoTim reviewed
Thx！

2022-02-04 04:40 UTC, leviding approved these changes

2022-02-04 04:40 UTC, merged